language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

# safelist
branches:
  only:
  - master
  - stable

install:
  - pip install -r requirements.txt
  - docker-compose up -d
  - gunicorn --daemon  --bind 0.0.0.0:9891 --workers 10 wsgi:app

script:
  - python3 test.py
  - python3 testsendreq.py
