language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

install:
  - ./rebuild.sh
  - pip install -r requirements.txt
  - docker-compose up -d

script:
  - python3 test.py
  - python3 testsendreq.py
