
version: '2.1'
services:

  jobsvc:
    image: artyins-saveservice
    restart: always
    volumes:
    - ./logs:/logs
    - ./config:/config
    healthcheck:
      test: wget --spider --quiet http://localhost:9891/test
    ports:
      - "9891:9891"